server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://rm-2vcj0c5x9fl4grz0i9o.mysql.cn-chengdu.rds.aliyuncs.com:3306/clouddb?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: YUFhNzM5NzcxNDA5
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cloud.entities

eureka:
  client:
    #是否注册进Eureka
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: payment8001
    prefer-ip-address: true
#    lease-renewal-interval-in-seconds: 1
#    lease-expiration-duration-in-seconds: 2