server:
  port: 8401

spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.25.132:80
    sentinel:
      transport:
        dashboard: 192.168.25.132:8858
        port: 8719
      datasource:
        ds1:
          nacos:
            server-addr: 192.168.25.132:80
            dataId: cloudalibaba-sentinel-service
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow

management:
  endpoints:
    web:
      exposure:
        include: "*"

feign:
  sentinel:
    enabled: true