server:
  port: 8401

spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.25.132:80
    sentinel:
      transport:
        dashboard: 192.168.25.132:8858
        port: 8719

management:
  endpoints:
    web:
      exposure:
        include: "*"