server:
  port: 2001

spring:
  application:
    name: seata-order-service
  cloud:
    alibaba:
      seata:
        tx-service-group: fsp_tx_group
    nacos:
      discovery:
        server-addr: 192.168.25.132:80
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-2vcj0c5x9fl4grz0i9o.mysql.cn-chengdu.rds.aliyuncs.com:3306/seata_order
    username: root
    password: YUFhNzM5NzcxNDA5

feign:
  hystrix:
    enabled: false

logging:
  level:
    io:
      seata: info

mybatis:
  mapper-locations: classpath:mapper/*.xml

banner-test:
  version: 1.0